#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# Copyright 2024-2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

"""SPSDK fuses functionality test module.

This module contains unit tests for the SPSDK fuses handling functionality,
specifically testing the FuseScript class and related fuse operations.
"""

from spsdk import version as spsdk_version
from spsdk.fuses.fuses import FuseScript
from spsdk.utils.database import DatabaseManager
from spsdk.utils.family import FamilyRevision


def test_fuse_script() -> None:
    """Test the FuseScript class functionality.

    Validates FuseScript initialization with family revision and database manager,
    verifies family properties, operator functionality, script naming, and file
    header generation with proper formatting and version information.
    """
    fuse_script = FuseScript(FamilyRevision("mimx9352", "a0"), DatabaseManager.AHAB)
    assert fuse_script.family.name == "mimx9352"
    assert fuse_script.family.revision == "a0"
    assert fuse_script.operator.NAME == "nxpele"
    assert fuse_script.name == "AHAB SRK"
    assert fuse_script.operator.get_fuse_write_cmd(0, 0) == "write-fuse --index 0 --data 0x0"
    assert (
        fuse_script.generate_file_header() == f"# nxpele AHAB SRK fuses programming script\n"
        f"# Generated by SPSDK {spsdk_version}\n"
        f"# Family: mimx9352, Revision: a0"
    )
