#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# Copyright 2024-2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

"""Test for fuses handling."""
from spsdk import version as spsdk_version
from spsdk.utils.database import DatabaseManager
from spsdk.fuses.fuses import FuseScript


def test_fuse_script():
    """Test FuseScript class."""
    fuse_script = FuseScript("mimx9352", "a0", DatabaseManager.AHAB)
    assert fuse_script.family == "mimx9352"
    assert fuse_script.revision == "a0"
    assert fuse_script.operator.NAME == "nxpele"
    assert fuse_script.name == "AHAB SRK"
    assert fuse_script.operator.get_fuse_write_cmd(0, 0) == "write-fuse --index 0 --data 0x0"
    assert (
        fuse_script.generate_file_header() == f"# nxpele AHAB SRK fuses programming script\n"
        f"# Generated by SPSDK {spsdk_version}\n"
        f"# Family: mimx9352 Revision: a0"
    )
